### PR TITLE
update to .net 7.0

### PR DESCRIPTION
**Pull request by ieviev**
I just updated the solution to .net 7, i was wondering if you'd push a new Nuget to the original repository, i want to use it for fsx scripting

### CODE REVIEW

**Comment by kekyo** [comment]
@aciq Thx PR, I will check soon.

**Comment by kekyo** [comment]
@aciq This repository hasn't been maintained for a while, so a lot of things were broken.
If you don't mind, I would like to merge it into devel once, and then re-tune it so that I can build it without problems in modern times, is that ok?

**Comment by ieviev** [comment]
yes, sounds very good. thank you

**Comment by kekyo** [comment]
@aciq  0.9.0 package is being deployed onto nuget.org.

However, I could not get through the regular route of the test project. Perhaps Roslyn has been upgraded, which caused the pattern match to not pass in some places. If you find out anything, please create an issue.

**Pull request merged**
